version: "3.8"
services:
  influx:
    image: influxdb:1.8
    container_name: influxc
    ports:
      - '8086:8086'
    volumes:
      - influxv:/var/lib/influxdb
      - $PWD/influxdb.conf:/etc/influxdb/influxdb.conf
    environment:
      INFLUXDB_ADMIN_USER: ${INFLUXDB_ADMIN_USER}
      INFLUXDB_ADMIN_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD}
      INFLUXDB_DB: ${INFLUX_DB}
  grafana:
    image: grafana/grafana-oss
    container_name: grafanac
    ports:
      - '3000:3000'
    volumes:
      - grafanav:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
volumes:
  influxv:
  grafanav:
